/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InstagramAccessTokenService } from "../instagramAccessToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InstagramAccessTokenCreateInput } from "./InstagramAccessTokenCreateInput";
import { InstagramAccessToken } from "./InstagramAccessToken";
import { InstagramAccessTokenFindManyArgs } from "./InstagramAccessTokenFindManyArgs";
import { InstagramAccessTokenWhereUniqueInput } from "./InstagramAccessTokenWhereUniqueInput";
import { InstagramAccessTokenUpdateInput } from "./InstagramAccessTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InstagramAccessTokenControllerBase {
  constructor(
    protected readonly service: InstagramAccessTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InstagramAccessToken })
  @nestAccessControl.UseRoles({
    resource: "InstagramAccessToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInstagramAccessToken(
    @common.Body() data: InstagramAccessTokenCreateInput
  ): Promise<InstagramAccessToken> {
    return await this.service.createInstagramAccessToken({
      data: data,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [InstagramAccessToken] })
  @ApiNestedQuery(InstagramAccessTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "InstagramAccessToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async instagramAccessTokens(
    @common.Req() request: Request
  ): Promise<InstagramAccessToken[]> {
    const args = plainToClass(InstagramAccessTokenFindManyArgs, request.query);
    return this.service.instagramAccessTokens({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InstagramAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InstagramAccessToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async instagramAccessToken(
    @common.Param() params: InstagramAccessTokenWhereUniqueInput
  ): Promise<InstagramAccessToken | null> {
    const result = await this.service.instagramAccessToken({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InstagramAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InstagramAccessToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInstagramAccessToken(
    @common.Param() params: InstagramAccessTokenWhereUniqueInput,
    @common.Body() data: InstagramAccessTokenUpdateInput
  ): Promise<InstagramAccessToken | null> {
    try {
      return await this.service.updateInstagramAccessToken({
        where: params,
        data: data,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InstagramAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InstagramAccessToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInstagramAccessToken(
    @common.Param() params: InstagramAccessTokenWhereUniqueInput
  ): Promise<InstagramAccessToken | null> {
    try {
      return await this.service.deleteInstagramAccessToken({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
