/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FacebookAccessTokenService } from "../facebookAccessToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FacebookAccessTokenCreateInput } from "./FacebookAccessTokenCreateInput";
import { FacebookAccessToken } from "./FacebookAccessToken";
import { FacebookAccessTokenFindManyArgs } from "./FacebookAccessTokenFindManyArgs";
import { FacebookAccessTokenWhereUniqueInput } from "./FacebookAccessTokenWhereUniqueInput";
import { FacebookAccessTokenUpdateInput } from "./FacebookAccessTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FacebookAccessTokenControllerBase {
  constructor(
    protected readonly service: FacebookAccessTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FacebookAccessToken })
  @nestAccessControl.UseRoles({
    resource: "FacebookAccessToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFacebookAccessToken(
    @common.Body() data: FacebookAccessTokenCreateInput
  ): Promise<FacebookAccessToken> {
    return await this.service.createFacebookAccessToken({
      data: data,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FacebookAccessToken] })
  @ApiNestedQuery(FacebookAccessTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FacebookAccessToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async facebookAccessTokens(
    @common.Req() request: Request
  ): Promise<FacebookAccessToken[]> {
    const args = plainToClass(FacebookAccessTokenFindManyArgs, request.query);
    return this.service.facebookAccessTokens({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FacebookAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FacebookAccessToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async facebookAccessToken(
    @common.Param() params: FacebookAccessTokenWhereUniqueInput
  ): Promise<FacebookAccessToken | null> {
    const result = await this.service.facebookAccessToken({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FacebookAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FacebookAccessToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFacebookAccessToken(
    @common.Param() params: FacebookAccessTokenWhereUniqueInput,
    @common.Body() data: FacebookAccessTokenUpdateInput
  ): Promise<FacebookAccessToken | null> {
    try {
      return await this.service.updateFacebookAccessToken({
        where: params,
        data: data,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FacebookAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FacebookAccessToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFacebookAccessToken(
    @common.Param() params: FacebookAccessTokenWhereUniqueInput
  ): Promise<FacebookAccessToken | null> {
    try {
      return await this.service.deleteFacebookAccessToken({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
