/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  FacebookAccessToken as PrismaFacebookAccessToken,
} from "@prisma/client";

export class FacebookAccessTokenServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FacebookAccessTokenCountArgs, "select">
  ): Promise<number> {
    return this.prisma.facebookAccessToken.count(args);
  }

  async facebookAccessTokens<T extends Prisma.FacebookAccessTokenFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.FacebookAccessTokenFindManyArgs>
  ): Promise<PrismaFacebookAccessToken[]> {
    return this.prisma.facebookAccessToken.findMany<Prisma.FacebookAccessTokenFindManyArgs>(
      args
    );
  }
  async facebookAccessToken<T extends Prisma.FacebookAccessTokenFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.FacebookAccessTokenFindUniqueArgs>
  ): Promise<PrismaFacebookAccessToken | null> {
    return this.prisma.facebookAccessToken.findUnique(args);
  }
  async createFacebookAccessToken<
    T extends Prisma.FacebookAccessTokenCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FacebookAccessTokenCreateArgs>
  ): Promise<PrismaFacebookAccessToken> {
    return this.prisma.facebookAccessToken.create<T>(args);
  }
  async updateFacebookAccessToken<
    T extends Prisma.FacebookAccessTokenUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FacebookAccessTokenUpdateArgs>
  ): Promise<PrismaFacebookAccessToken> {
    return this.prisma.facebookAccessToken.update<T>(args);
  }
  async deleteFacebookAccessToken<
    T extends Prisma.FacebookAccessTokenDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.FacebookAccessTokenDeleteArgs>
  ): Promise<PrismaFacebookAccessToken> {
    return this.prisma.facebookAccessToken.delete(args);
  }
}
