/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  TwitterAccessToken as PrismaTwitterAccessToken,
} from "@prisma/client";

export class TwitterAccessTokenServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.TwitterAccessTokenCountArgs, "select">
  ): Promise<number> {
    return this.prisma.twitterAccessToken.count(args);
  }

  async twitterAccessTokens<T extends Prisma.TwitterAccessTokenFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.TwitterAccessTokenFindManyArgs>
  ): Promise<PrismaTwitterAccessToken[]> {
    return this.prisma.twitterAccessToken.findMany<Prisma.TwitterAccessTokenFindManyArgs>(
      args
    );
  }
  async twitterAccessToken<T extends Prisma.TwitterAccessTokenFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.TwitterAccessTokenFindUniqueArgs>
  ): Promise<PrismaTwitterAccessToken | null> {
    return this.prisma.twitterAccessToken.findUnique(args);
  }
  async createTwitterAccessToken<T extends Prisma.TwitterAccessTokenCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TwitterAccessTokenCreateArgs>
  ): Promise<PrismaTwitterAccessToken> {
    return this.prisma.twitterAccessToken.create<T>(args);
  }
  async updateTwitterAccessToken<T extends Prisma.TwitterAccessTokenUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.TwitterAccessTokenUpdateArgs>
  ): Promise<PrismaTwitterAccessToken> {
    return this.prisma.twitterAccessToken.update<T>(args);
  }
  async deleteTwitterAccessToken<T extends Prisma.TwitterAccessTokenDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.TwitterAccessTokenDeleteArgs>
  ): Promise<PrismaTwitterAccessToken> {
    return this.prisma.twitterAccessToken.delete(args);
  }
}
