/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LinkedInAccessTokenService } from "../linkedInAccessToken.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LinkedInAccessTokenCreateInput } from "./LinkedInAccessTokenCreateInput";
import { LinkedInAccessToken } from "./LinkedInAccessToken";
import { LinkedInAccessTokenFindManyArgs } from "./LinkedInAccessTokenFindManyArgs";
import { LinkedInAccessTokenWhereUniqueInput } from "./LinkedInAccessTokenWhereUniqueInput";
import { LinkedInAccessTokenUpdateInput } from "./LinkedInAccessTokenUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LinkedInAccessTokenControllerBase {
  constructor(
    protected readonly service: LinkedInAccessTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LinkedInAccessToken })
  @nestAccessControl.UseRoles({
    resource: "LinkedInAccessToken",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLinkedInAccessToken(
    @common.Body() data: LinkedInAccessTokenCreateInput
  ): Promise<LinkedInAccessToken> {
    return await this.service.createLinkedInAccessToken({
      data: data,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LinkedInAccessToken] })
  @ApiNestedQuery(LinkedInAccessTokenFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LinkedInAccessToken",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async linkedInAccessTokens(
    @common.Req() request: Request
  ): Promise<LinkedInAccessToken[]> {
    const args = plainToClass(LinkedInAccessTokenFindManyArgs, request.query);
    return this.service.linkedInAccessTokens({
      ...args,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LinkedInAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LinkedInAccessToken",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async linkedInAccessToken(
    @common.Param() params: LinkedInAccessTokenWhereUniqueInput
  ): Promise<LinkedInAccessToken | null> {
    const result = await this.service.linkedInAccessToken({
      where: params,
      select: {
        accessToken: true,
        createdAt: true,
        expirationDate: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LinkedInAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LinkedInAccessToken",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLinkedInAccessToken(
    @common.Param() params: LinkedInAccessTokenWhereUniqueInput,
    @common.Body() data: LinkedInAccessTokenUpdateInput
  ): Promise<LinkedInAccessToken | null> {
    try {
      return await this.service.updateLinkedInAccessToken({
        where: params,
        data: data,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LinkedInAccessToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LinkedInAccessToken",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLinkedInAccessToken(
    @common.Param() params: LinkedInAccessTokenWhereUniqueInput
  ): Promise<LinkedInAccessToken | null> {
    try {
      return await this.service.deleteLinkedInAccessToken({
        where: params,
        select: {
          accessToken: true,
          createdAt: true,
          expirationDate: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
